---
# absolute path required
web_root: '/var/www/html'
# favicon, can take any image type
favicon: 'favicon_smile.gif'
# domain name, or whatever you want the tab in the browser to say
website_title: 'jessebot.work'
# the default image shown at the front of the page
image: './my_picture.png'
# Your name
name: 'Jesse Hitch'
# Job Title
occupation: 'DevOps Engineer'
# Skills - what you're good at.
skills: ['linux', 'devops']
# things you like
likes: ['videogames', 'analogies', 'silly hair']
# Full URL to your github
github_URL: 'https://github.com/jessebot'
# Full URL to your linkedin public profile
linkedin_URL: 'https://www.linkedin.com/in/jesse-hitch-8b5b023a/'
# complete google doc sharing URL, assuming this is public
resume_live_doc_URL: 'https://docs.google.com/document/d/blahblahblah'
# in your google doc, you can go to download as and right click copy that
# URL, or you can host a live copy at another URL
resume_pdf_URL: ''
# setting to false will remove fork me corner banner
fork_me: True
# Boolean, if set to True, will generate new panel with below info
optional_panel: True
# this could be social media, other conent, whatever suits you!
opt_panel_title: "Linux Newbie Class"
opt_panel_image: "penguin_copy.png"
opt_panel_button_text: "How To Unix/Linux"
opt_panel_URL: "http://howtonix.info/"
