---
# favicon, can take any image type
favicon: 'favicon.ico'
# URL to the website
website_url: 'https://murr.club/banana'
# domain name, or whatever you want the tab in the browser to say
website_title: "Banana"
# set to false to remove fork me banner in uppper right corner
fork_me: false


# image shown at the front of the page, this should be in /static/img
profile_image: 'my_picture.png'
# image alt text
profile_image_alt: 'Portrait selfie of an anthromorphic hyena with yellow fur, brown spots, green eyes and a green mohawk. He is smiling.'
# Your name
name: 'Banana'
# Pronouns
pronouns: 'he/him'
# blurb about yourself
blurb: "I'm a big fluffy hyena that loves to chill and make new friends! I do IT stuff for work and I'm always learning new things. My fursuit maker is https://twitter.com/wolf_daz."

# Job Title
occupation: 'Cloud Yeen'
# Skills - what you're good at.
skills:
  - linux
  - devops
  - webhosting
  - being cute

# This is for a section to humanize the user
likes:
  - sleeping
  - cuddles
  - parties
  - video games

# social links you want to display on the profile
social_links:
  twitter:
    # Full URL to your social link
    URL: 'https://twitter.com/bananayeen'
    # can be any glyph in nerdfonts
    icon: 'nf-fa-twitter_square'
  telegram:
    URL: 'https://t.me/uwuBanana'
    icon: "nf-fa-telegram"

# this can be from any provider, but has to download a PDF file
resume_pdf_URL: "https://t.me/addstickers/IAMuwuBANANA"
